    HW_ver_gpio u_HW_ver_gpio(.gpio_i(gpio_i),
        .gpio_o(gpio_o),
        .gpio_en_o(gpio_en_o),
        .clk_i(clk_i),
        .resetn_i(resetn_i),
        .apb_penable_i(apb_penable_i),
        .apb_psel_i(apb_psel_i),
        .apb_pwrite_i(apb_pwrite_i),
        .apb_paddr_i(apb_paddr_i),
        .apb_pwdata_i(apb_pwdata_i),
        .apb_prdata_o(apb_prdata_o),
        .apb_pslverr_o(apb_pslverr_o),
        .apb_pready_o(apb_pready_o),
        .int_o(int_o));
