#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

if {![file exists {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/impl_1}]} {
  file mkdir {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/impl_1}
}
cd {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/impl_1}

sys_set_attribute -gui on -msg {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/promote.xml}
msg_load {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/promote.xml}
des_set_project_udb -in {u23_lifcl_nx33u_evalbd_ibd_impl_1_syn.udb} -out {u23_lifcl_nx33u_evalbd_ibd_impl_1_map.udb} -milestone map -pm jd5u00a
des_set_reference_udb -clean
map_set_option {pdc_file "C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/pdc/u23_lifcl_nx33u_evalbd_ibd.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false}
map_run

} out]} {
   puts $out
   set ret 1
}
exit -force ${ret}
