#-- Lattice Semiconductor Corporation Ltd.
#-- Bitgen run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/promote.xml}
msg_load {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/promote.xml}
des_set_project_udb -in {u23_lifcl_nx33u_evalbd_ibd_impl_1.udb} -milestone bit -pm jd5u00a
# bitgen option
bit_set_option { enable_early_io_wakeup false output_format "binary"   ip_evaluation false register_initialization true bitstream_mode normal }
#-- write result file
bit_generate -w {C:/Users/whan/Documents/AppProject/USB_LIFCL_NX33U/RD_IOA_USB2_REVB/Design/impl_1/u23_lifcl_nx33u_evalbd_ibd_impl_1}

} out]} {
   puts $out
   set ret 1
}

exit -force ${ret}
