/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2023.2.0.38.1
    Soft IP Version: 1.8.0
    2024 02 15 12:31:22
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_60m (clki_i, clkop_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    output  clkop_o;
    output  lock_o;
endmodule