    lscc_spis1 __(.clk_i( ),
        .rst_n_i( ),
        .sclk_i( ),
        .mosi_i( ),
        .miso_o( ),
        .ss_i( ),
        .int_o( ),
        .apb_penable_i( ),
        .apb_psel_i( ),
        .apb_pwrite_i( ),
        .apb_paddr_i( ),
        .apb_pwdata_i( ),
        .apb_pready_o( ),
        .apb_pslverr_o( ),
        .apb_prdata_o( ));
