/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2024.2.2410282205
    Soft IP Version: 1.0.0
    2024 11 06 17:00:59
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module u23_config_intf_feedthrough (ahbl_hsel_slv_i, ahbl_haddr_slv_i,
    ahbl_hburst_slv_i, ahbl_hsize_slv_i, ahbl_hmastlock_slv_i,
    ahbl_hprot_slv_i, ahbl_htrans_slv_i, ahbl_hwdata_slv_i, ahbl_hwrite_slv_i,
    ahbl_hready_slv_i, ahbl_hreadyout_slv_o, ahbl_hresp_slv_o,
    ahbl_hrdata_slv_o, ahbl_hsel_mstr_o, ahbl_haddr_mstr_o, ahbl_hburst_mstr_o,
    ahbl_hsize_mstr_o, ahbl_hmastlock_mstr_o, ahbl_hprot_mstr_o,
    ahbl_htrans_mstr_o, ahbl_hwdata_mstr_o, ahbl_hwrite_mstr_o,
    ahbl_hready_mstr_o, ahbl_hready_mstr_i, ahbl_hresp_mstr_i,
    ahbl_hrdata_mstr_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ahbl_hsel_slv_i;
    input  [16:0]  ahbl_haddr_slv_i;
    input  [2:0]  ahbl_hburst_slv_i;
    input  [2:0]  ahbl_hsize_slv_i;
    input  ahbl_hmastlock_slv_i;
    input  [3:0]  ahbl_hprot_slv_i;
    input  [1:0]  ahbl_htrans_slv_i;
    input  [31:0]  ahbl_hwdata_slv_i;
    input  ahbl_hwrite_slv_i;
    input  ahbl_hready_slv_i;
    output  ahbl_hreadyout_slv_o;
    output  ahbl_hresp_slv_o;
    output  [31:0]  ahbl_hrdata_slv_o;
    output  ahbl_hsel_mstr_o;
    output  [16:0]  ahbl_haddr_mstr_o;
    output  [2:0]  ahbl_hburst_mstr_o;
    output  [2:0]  ahbl_hsize_mstr_o;
    output  ahbl_hmastlock_mstr_o;
    output  [3:0]  ahbl_hprot_mstr_o;
    output  [1:0]  ahbl_htrans_mstr_o;
    output  [31:0]  ahbl_hwdata_mstr_o;
    output  ahbl_hwrite_mstr_o;
    output  ahbl_hready_mstr_o;
    input  ahbl_hready_mstr_i;
    input  ahbl_hresp_mstr_i;
    input  [31:0]  ahbl_hrdata_mstr_i;
endmodule