--  >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
--	  ------------------------------------------------------------------
--	  Copyright(c) 2019 - 2024 by Lattice Semiconductor Corporation
--      ALL RIGHTS RESERVED
--	  ------------------------------------------------------------------

--	  IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
--DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.

--	   Lattice grants permission to use this code pursuant to the
--       terms of the Lattice Propel License Agreement.

--     DISCLAIMER :

--       LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
--EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE PROPEL
--LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE SPECIFICALLY
--DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR A
--PARTICULAR PURPOSE.LATTICE DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED
--HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT LICENSEE'S OPERATION OF
--ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE OR ITS CONTENTS WILL BE
--UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS HEREIN WILL BE CORRECTED.
--LICENSEE ASSUMES RESPONSIBILITY FOR SELECTION OF MATERIALS TO ACHIEVE ITS
--INTENDED RESULTS, AND FOR THE PROPER INSTALLATION, USE, AND RESULTS 
--OBTAINED THEREFROM.LICENSEE ASSUMES THE ENTIRE RISK OF THE FILE AND ITS 
--CONTENTS PROVING DEFECTIVE OR FAILING TO PERFORM PROPERLY AND IN SUCH 
--EVENT, LICENSEE SHALL ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, 
--SERVICE, CORRECTION, OR ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR 
--ASSOCIATED WITH THE SOFTWARE.IN NO EVENT SHALL LATTICE BE LIABLE TO ANY 
--PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, 
--INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS 
--CONTENTS, EVEN IF LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH 
--DAMAGES.LATTICE'S SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH 
--ABOVE.LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS 
--OR USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY 
--RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY THE 
--USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE USE OF 
--FORMAL SOFTWARE VALIDATION METHODS.

--     ------------------------------------------------------------------

--VHDL instantiation template

component u23_lifclu_nx33_prpl_bldr_des is
    port (HW_ver_i: in std_logic_vector(31 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_haddr_slv_i_portbus: in std_logic_vector(31 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hburst_slv_i_portbus: in std_logic_vector(2 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hprot_slv_i_portbus: in std_logic_vector(3 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hrdata_slv_o_portbus: out std_logic_vector(31 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hsize_slv_i_portbus: in std_logic_vector(2 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_htrans_slv_i_portbus: in std_logic_vector(1 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hwdata_slv_i_portbus: in std_logic_vector(31 downto 0);
        gpio_0_z: inout std_logic_vector(1 downto 0);
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_haddr_mstr_o_portbus: out std_logic_vector(16 downto 0);
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hburst_mstr_o_portbus: out std_logic_vector(2 downto 0);
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hprot_mstr_o_portbus: out std_logic_vector(3 downto 0);
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hrdata_mstr_i_portbus: in std_logic_vector(31 downto 0);
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hsize_mstr_o_portbus: out std_logic_vector(2 downto 0);
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_htrans_mstr_o_portbus: out std_logic_vector(1 downto 0);
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hwdata_mstr_o_portbus: out std_logic_vector(31 downto 0);
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hmastlock_slv_i_port: in std_logic;
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hready_slv_i_port: in std_logic;
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hreadyout_slv_o_port: out std_logic;
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hresp_slv_o_port: out std_logic;
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hsel_slv_i_port: in std_logic;
        ahbl0_inst_AHBL_S01_interface_ahbl_s01_hwrite_slv_i_port: in std_logic;
        clk_i: in std_logic;
        cpu0_inst_IRQ_S1_interface_irq1_i_port: in std_logic;
        i2cm0_scl: inout std_logic;
        i2cm0_sda: inout std_logic;
        rstn_i: in std_logic;
        spim0_miso_i: in std_logic;
        spim0_mosi_o: out std_logic;
        spim0_sclk_o: out std_logic;
        spim0_ssn_o: out std_logic;
        system_reset_n_o: out std_logic;
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hmastlock_mstr_o_port: out std_logic;
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hready_mstr_i_port: in std_logic;
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hready_mstr_o_port: out std_logic;
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hresp_mstr_i_port: in std_logic;
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hsel_mstr_o_port: out std_logic;
        u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hwrite_mstr_o_port: out std_logic;
        uart_rxd_i: in std_logic;
        uart_txd_o: out std_logic
    );
    
end component u23_lifclu_nx33_prpl_bldr_des;
_inst: u23_lifclu_nx33_prpl_bldr_des port map (cpu0_inst_IRQ_S1_interface_irq1_i_port => __,
                                               
                                               rstn_i => __,
                                               system_reset_n_o => __,
                                               gpio_0_z => __,
                                               i2cm0_scl => __,
                                               i2cm0_sda => __,
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_haddr_slv_i_portbus => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hburst_slv_i_portbus => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hprot_slv_i_portbus => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hrdata_slv_o_portbus => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hsize_slv_i_portbus => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_htrans_slv_i_portbus => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hwdata_slv_i_portbus => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hmastlock_slv_i_port => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hready_slv_i_port => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hreadyout_slv_o_port => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hresp_slv_o_port => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hsel_slv_i_port => __,
                                               
                                               ahbl0_inst_AHBL_S01_interface_ahbl_s01_hwrite_slv_i_port => __,
                                               
                                               HW_ver_i => __,
                                               clk_i => __,
                                               spim0_miso_i => __,
                                               spim0_mosi_o => __,
                                               spim0_sclk_o => __,
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_haddr_mstr_o_portbus => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hburst_mstr_o_portbus => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hprot_mstr_o_portbus => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hrdata_mstr_i_portbus => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hsize_mstr_o_portbus => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_htrans_mstr_o_portbus => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hwdata_mstr_o_portbus => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hmastlock_mstr_o_port => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hready_mstr_i_port => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hready_mstr_o_port => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hresp_mstr_i_port => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hsel_mstr_o_port => __,
                                               
                                               u23_config_intf_feedthrough_inst_AHBL_M0_interface_ahbl_hwrite_mstr_o_port => __,
                                               
                                               uart_rxd_i => __,
                                               uart_txd_o => __);
                                               